# Kafka TCP Load Balancing
upstream kafka_cluster {
    server kafka-broker-1:9092;
    server kafka-broker-2:9092;
    server kafka-broker-3:9092;
}

server {
    listen 9092;
    proxy_pass kafka_cluster;
    proxy_connect_timeout 1s;
}

# MQTT TCP Load Balancing
upstream mqtt_cluster {
    server mqtt-kafka-bridge:1883;
}

server {
    listen 1883;
    proxy_pass mqtt_cluster;
    proxy_connect_timeout 1s;
}
